export const TodoAction = {
    remote: {
        FETCH_TODO_BY_SLUG: 'FETCH_TODO_BY_SLUG',
        FETCH_TODOS: 'FETCH_TODOS',
        FETCH_TODOS_BY_SLUG: 'FETCH_TODOS_BY_SLUG',
        FETCH_TODOS_BY_CATEGORY: 'FETCH_TODOS_BY_CATEGORY',
        CREATE_TODO: 'CREATE_TODO',
        UPDATE_TODO: 'UPDATE_TODO',
        DELETE_TODO: 'DELETE_TODO',
    },
    local: {
        FETCH_TODO_SUCCESS: 'FETCH_TODO_SUCCESS',
        FETCH_TODOS_SUCCESS: 'FETCH_TODOS_SUCCESS',
        FETCH_TODOS_BY_SLUG_SUCCESS: 'FETCH_TODOS_BY_SLUG_SUCCESS',
        CREATE_TODO_SUCCESS: 'CREATE_TODO_SUCCESS',
        UPDATE_TODO_SUCCESS: 'UPDATE_TODO_SUCCESS',
        DELETE_TODO_SUCCESS: 'DELETE_TODO_SUCCESS',
        CLEAR_TODO_SELECTED: 'CLEAR_TODO_SELECTED',
        TODO_SET_IS_LOADING: 'TODO_SET_IS_LOADING',
        CHANGE_TODO: 'CHANGE_TODO',
        CLEAR_TODO_CREATED: 'CLEAR_TODO_CREATED',
        CLEAR_TODO_DELETED: 'CLEAR_TODO_DELETED'
    }
};

export const AuthAction = {
    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    LOGIN_FAILURE: 'LOGIN_FAILURE',
    LOGOUT: 'LOGOUT',
    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAILURE: 'REGISTER_FAILURE',
    AUTH_ERROR: 'AUTH_ERROR',
    GET_ALL: 'GET_ALL',
    GET_ALL_SUCCESS: 'GET_ALL_SUCCESS',
    GET_ALL_FAILURE: 'GET_ALL_FAILURE',
    DELETE: 'DELETE',
    DELETE_SUCCESS: 'DELETE_SUCCESS',
    DELETE_FAILURE: 'DELETE_FAILURE'
};

export const UiAction = {
    TOAST_SUCCESS: 'TOAST_SUCCESS',
    TOAST_ERROR: 'TOAST_ERROR',
    TOAST_CLEAR: 'TOAST_CLEAR',
    TOAST_INFO: 'TOAST_INFO',
    TOAST_SHOW: 'TOAST_SHOW',

    // Not implemented yet the below
    MESSAGE_CLEAR_SUCCESS: 'MESSAGE_CLEAR_SUCCESS',
    MESSAGE_CLEAR_ERROR: 'MESSAGE_CLEAR_ERROR',
    MESSAGE_CLEAR_INFO: 'MESSAGE_CLEAR_INFO',
    MESSAGE_CLEAR: 'MESSAGE_CLEAR',

    DIALOG_ERROR: 'DIALOG_ERROR',
    DIALOG_CLEAR: 'DIALOG_CLEAR'
};

export const CategoryAction = {
    remote: {
        FETCH_CATEGORIES: 'FETCH_CATEGORIES',
    },
    local: {
        CATEGORY_SET_IS_LOADING: 'CATEGORY_SET_IS_LOADING',
        FETCH_CATEGORIES_SUCCESS: 'FETCH_CATEGORIES_SUCCESS',
    }
};

export const TagAction = {
    remote: {
        FETCH_TAGS: 'FETCH_TAGS',
    },
    local: {
        TAG_SET_IS_LOADING: 'TAG_SET_IS_LOADING',
        FETCH_TAGS_SUCCESS: 'FETCH_TAGS_SUCCESS',
    }
};

